# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC-Udemy-Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC-Udemy-Study
  pod 'Alamofire'
  # url -> image
  pod 'Kingfisher', '~> 7.0'

  pod 'LoadingShimmer'

  target 'UMC-Udemy-StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC-Udemy-StudyUITests' do
    # Pods for testing
  end

end
