# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC-Mission-Week6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC-Mission-Week6
  pod 'Alamofire'
  # url to Image
  pod 'Kingfisher', '~> 7.0'
  # Show Skeleton Animation on View
  pod 'LoadingShimmer'

  target 'UMC-Mission-Week6Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC-Mission-Week6UITests' do
    # Pods for testing
  end

end
