# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC-Mission-Week7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC-Mission-Week7
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

  pod 'Kingfisher'


  target 'UMC-Mission-Week7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC-Mission-Week7UITests' do
    # Pods for testing
  end

end
